### ISSUE TITLE
Create code example for play

### ISSUE THREAD

**Issue by lforite** [lforite/rio-talk#1]
# Description
Create code example to showcase the use of `RIO` in a Play application

# Tasks
- [ ] create a Play app
- [ ] create a route / service / http client using `RIO` abstraction
- [ ] show some basic tests
